/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class DoubleVector extends java.util.AbstractList<Double> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DoubleVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DoubleVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CoolPropJNI.delete_DoubleVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DoubleVector(double[] initialElements) {
    this();
    reserve(initialElements.length);

    for (double element : initialElements) {
      add(element);
    }
  }

  public DoubleVector(Iterable<Double> initialElements) {
    this();
    for (double element : initialElements) {
      add(element);
    }
  }

  public Double get(int index) {
    return doGet(index);
  }

  public Double set(int index, Double e) {
    return doSet(index, e);
  }

  public boolean add(Double e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, Double e) {
    modCount++;
    doAdd(index, e);
  }

  public Double remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public DoubleVector() {
    this(CoolPropJNI.new_DoubleVector__SWIG_0(), true);
  }

  public DoubleVector(DoubleVector other) {
    this(CoolPropJNI.new_DoubleVector__SWIG_1(DoubleVector.getCPtr(other), other), true);
  }

  public long capacity() {
    return CoolPropJNI.DoubleVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    CoolPropJNI.DoubleVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return CoolPropJNI.DoubleVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    CoolPropJNI.DoubleVector_clear(swigCPtr, this);
  }

  public DoubleVector(int count, double value) {
    this(CoolPropJNI.new_DoubleVector__SWIG_2(count, value), true);
  }

  private int doSize() {
    return CoolPropJNI.DoubleVector_doSize(swigCPtr, this);
  }

  private void doAdd(double x) {
    CoolPropJNI.DoubleVector_doAdd__SWIG_0(swigCPtr, this, x);
  }

  private void doAdd(int index, double x) {
    CoolPropJNI.DoubleVector_doAdd__SWIG_1(swigCPtr, this, index, x);
  }

  private double doRemove(int index) {
    return CoolPropJNI.DoubleVector_doRemove(swigCPtr, this, index);
  }

  private double doGet(int index) {
    return CoolPropJNI.DoubleVector_doGet(swigCPtr, this, index);
  }

  private double doSet(int index, double val) {
    return CoolPropJNI.DoubleVector_doSet(swigCPtr, this, index, val);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    CoolPropJNI.DoubleVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
